#create albums and tracks
Album.create([
	{ name: "The Dark Side of the Moon", state: "draft" },
	{ name: "The Wall", state: "draft" },
	{ name: "Wish You Were Here", state: "draft" },
	{ name: "Animals", state: "draft" },
	{ name: "The Final Cut", state: "draft" },
	{ name: "A Momentary Lapse of Reason", state: "draft" },
	{ name: "The Division Bell", state: "draft" }
])

Track.create([
	{ album_id: 1, title: "Speak to Me", artist_name: "Pink Floyd", duration: 90 },
	{ album_id: 1, title: "Breathe", artist_name: "Pink Floyd", duration: 163 },
	{ album_id: 1, title: "On the Run", artist_name: "Pink Floyd", duration: 216 },
	{ album_id: 1, title: "Time", artist_name: "Pink Floyd", duration: 421 },
	{ album_id: 1, title: "The Great Gig in the Sky", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 1, title: "Money", artist_name: "Pink Floyd", duration: 382 },
	{ album_id: 1, title: "Us and Them", artist_name: "Pink Floyd", duration: 462 },
	{ album_id: 1, title: "Any Colour You Like", artist_name: "Pink Floyd", duration: 205 },
	{ album_id: 1, title: "Brain Damage", artist_name: "Pink Floyd", duration: 228 },
	{ album_id: 1, title: "Eclipse", artist_name: "Pink Floyd", duration: 122 },
	{ album_id: 2, title: "In the Flesh?", artist_name: "Pink Floyd", duration: 193 },
	{ album_id: 2, title: "The Thin Ice", artist_name: "Pink Floyd", duration: 134 },
	{ album_id: 2, title: "Another Brick in the Wall, Part 1", artist_name: "Pink Floyd", duration: 193 },
	{ album_id: 2, title: "The Happiest Days of Our Lives", artist_name: "Pink Floyd", duration: 111 },
	{ album_id: 2, title: "Another Brick in the Wall, Part 2", artist_name: "Pink Floyd", duration: 242 },
	{ album_id: 2, title: "Mother", artist_name: "Pink Floyd", duration: 320 },
	{ album_id: 2, title: "Goodbye Blue Sky", artist_name: "Pink Floyd", duration: 122 },
	{ album_id: 2, title: "Empty Spaces", artist_name: "Pink Floyd", duration: 108 },
	{ album_id: 2, title: "Young Lust", artist_name: "Pink Floyd", duration: 203 },
	{ album_id: 2, title: "One of My Turns", artist_name: "Pink Floyd", duration: 223 },
	{ album_id: 2, title: "Don't Leave Me Now", artist_name: "Pink Floyd", duration: 221 },
	{ album_id: 2, title: "Another Brick in the Wall, Part 3", artist_name: "Pink Floyd", duration: 91 },
	{ album_id: 2, title: "Goodbye Cruel World", artist_name: "Pink Floyd", duration: 89 },
	{ album_id: 3, title: "Shine On You Crazy Diamond, Part 1", artist_name: "Pink Floyd", duration: 810 },
	{ album_id: 3, title: "Welcome to the Machine", artist_name: "Pink Floyd", duration: 448 },
	{ album_id: 3, title: "Have a Cigar", artist_name: "Pink Floyd", duration: 310 },
	{ album_id: 3, title: "Wish You Were Here", artist_name: "Pink Floyd", duration: 335 },
	{ album_id: 3, title: "Shine On You Crazy Diamond, Part 2", artist_name: "Pink Floyd", duration: 754 },
	{ album_id: 4, title: "Pigs on the Wing, Part 1", artist_name: "Pink Floyd", duration: 108 },
	{ album_id: 4, title: "Dogs", artist_name: "Pink Floyd", duration: 1042 },
	{ album_id: 4, title: "Pigs (Three Different Ones)", artist_name: "Pink Floyd", duration: 1135 },
	{ album_id: 4, title: "Sheep", artist_name: "Pink Floyd", duration: 767 },
	{ album_id: 4, title: "Pigs on the Wing, Part 2", artist_name: "Pink Floyd", duration: 94 },
	{ album_id: 5, title: "The Post War Dream", artist_name: "Pink Floyd", duration: 143 },
	{ album_id: 5, title: "Your Possible Pasts", artist_name: "Pink Floyd", duration: 286 },
	{ album_id: 5, title: "One of the Few", artist_name: "Pink Floyd", duration: 94 },
	{ album_id: 5, title: "When the Tigers Broke Free", artist_name: "Pink Floyd", duration: 191 },
	{ album_id: 5, title: "The Hero's Return", artist_name: "Pink Floyd", duration: 122 },
	{ album_id: 5, title: "The Gunner's Dream", artist_name: "Pink Floyd", duration: 336 },
	{ album_id: 5, title: "Paranoid Eyes", artist_name: "Pink Floyd", duration: 286 },
	{ album_id: 5, title: "Get Your Filthy Hands Off My Desert", artist_name: "Pink Floyd", duration: 126 },
	{ album_id: 5, title: "The Fletcher Memorial Home", artist_name: "Pink Floyd", duration: 287 },
	{ album_id: 5, title: "Southampton Dock", artist_name: "Pink Floyd", duration: 122 },
	{ album_id: 5, title: "The Final Cut", artist_name: "Pink Floyd", duration: 286 },
	{ album_id: 5, title: "Not Now John", artist_name: "Pink Floyd", duration: 336 },
	{ album_id: 5, title: "Two Suns in the Sunset", artist_name: "Pink Floyd", duration: 336 },
	{ album_id: 6, title: "Signs of Life", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "Learning to Fly", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "The Dogs of War", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "One Slip", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "On the Turning Away", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "Yet Another Movie", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "Round and Around", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "A New Machine, Part 1", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "Terminal Frost", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "A New Machine, Part 2", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 6, title: "Sorrow", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 7, title: "Cluster One", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 7, title: "What Do You Want from Me", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 7, title: "Poles Apart", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 7, title: "Marooned", artist_name: "Pink Floyd", duration: 276 },
	{ album_id: 7, title: "A Great Day for Freedom", artist_name: "Pink Floyd", duration: 276 },
])